use std::path::PathBuf;

use rayon::prelude::*;

use crate::config::Config;
use crate::rules::CleanupRule;
use crate::scanner::entry::{Category, SafetyLevel, ScannedEntry};
use crate::scanner::project_index::PROJECT_INDEX;
use crate::scanner::walker;

/// Build artifacts: compiler/build tool output that can be regenerated by rebuilding.
const BUILD_MARKERS: &[(&str, &str, &str)] = &[
    // Rust
    ("target", "Cargo.toml", "Rust target/"),
    // Swift
    (".build", "Package.swift", "Swift .build/"),
    // Java (Maven)
    ("target", "pom.xml", "Maven target/"),
    // Java/Kotlin (Gradle)
    ("build", "build.gradle", "Gradle build/"),
    ("build", "build.gradle.kts", "Gradle build/"),
    // Elixir
    ("_build", "mix.exs", "Elixir _build/"),
];

/// Installed dependencies: downloaded packages that can be regenerated by reinstalling.
const DEPS_MARKERS: &[(&str, &str, &str)] = &[
    // Node.js
    ("node_modules", "package.json", "node_modules/"),
    // Python
    (".venv", "pyproject.toml", "Python .venv/"),
    (".venv", "requirements.txt", "Python .venv/"),
    (".venv", "setup.py", "Python .venv/"),
    ("venv", "pyproject.toml", "Python venv/"),
    ("venv", "requirements.txt", "Python venv/"),
    ("venv", "setup.py", "Python venv/"),
    (".tox", "tox.ini", "Python .tox/"),
    (".tox", "pyproject.toml", "Python .tox/"),
    // PHP
    ("vendor", "composer.json", "PHP vendor/"),
    // Ruby
    ("vendor", "Gemfile", "Ruby vendor/"),
    // Dart/Flutter
    (".dart_tool", "pubspec.yaml", "Dart .dart_tool/"),
];

pub struct BuildArtifactRule;
pub struct InstalledDepsRule;

fn collect_entries(dirs: &[(PathBuf, &'static str)], category: Category) -> Vec<ScannedEntry> {
    let mut entries: Vec<ScannedEntry> = dirs
        .par_iter()
        .filter_map(|(path, description)| {
            let (size, count) = walker::dir_size_and_count(path);
            if size > 0 {
                Some(ScannedEntry {
                    path: path.clone(),
                    size,
                    category,
                    safety: SafetyLevel::Safe,
                    description: (*description).to_owned(),
                    item_count: Some(count),
                })
            } else {
                None
            }
        })
        .collect();

    // Aggregate workspace-level entries into the root project entry.
    // If project B is inside project A (same label, B's parent starts with A's parent),
    // sum B's size into A and drop B. The total stays identical because we add before removing.
    // e.g. monorepo/packages/a/node_modules size merges into monorepo/node_modules
    entries.sort_by(|a, b| a.path.cmp(&b.path));
    entries.dedup_by(|later, earlier| {
        let dominated = later.description == earlier.description
            && later
                .path
                .parent()
                .is_some_and(|lp| earlier.path.parent().is_some_and(|ep| lp.starts_with(ep)));
        if dominated {
            earlier.size += later.size;
            if let (Some(ec), Some(lc)) = (&mut earlier.item_count, later.item_count) {
                *ec += lc;
            }
        }
        dominated
    });

    entries
}

impl CleanupRule for BuildArtifactRule {
    fn name(&self) -> &'static str {
        "Build Artifacts"
    }

    fn category(&self) -> Category {
        Category::BuildArtifact
    }

    fn scan(&self, _config: &Config) -> Vec<ScannedEntry> {
        let home = dirs::home_dir().unwrap_or_default();
        let mut dirs = PROJECT_INDEX.find_matching_dirs(BUILD_MARKERS);

        // Xcode DerivedData
        let derived_data = home.join("Library/Developer/Xcode/DerivedData");
        if derived_data.exists() {
            dirs.push((derived_data, "Xcode DerivedData"));
        }

        // Gradle caches
        let gradle_home = home.join(".gradle/caches");
        if gradle_home.exists() {
            dirs.push((gradle_home, "Gradle caches"));
        }

        collect_entries(&dirs, Category::BuildArtifact)
    }
}

impl CleanupRule for InstalledDepsRule {
    fn name(&self) -> &'static str {
        "Installed Dependencies"
    }

    fn category(&self) -> Category {
        Category::InstalledDeps
    }

    fn scan(&self, _config: &Config) -> Vec<ScannedEntry> {
        let dirs = PROJECT_INDEX.find_matching_dirs(DEPS_MARKERS);
        collect_entries(&dirs, Category::InstalledDeps)
    }
}

pub fn rules() -> Vec<Box<dyn CleanupRule>> {
    vec![Box::new(BuildArtifactRule), Box::new(InstalledDepsRule)]
}
